# Generated by Django 3.2.9 on 2021-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'incoming'), ('outgoing', 'outgoing')], default='push', max_length=8)),
                ('protocol', models.CharField(choices=[('webrtc', 'WebRTC'), ('rtmp', 'RTMP'), ('srt', 'SRT'), ('hls', 'HLS'), ('dash', 'DASH'), ('lldash', 'LLDASH')], default='rtmp', max_length=6)),
                ('application', models.CharField(default='default', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
