# Generated by Django 3.2.9 on 2021-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vhost', models.CharField(default='default', max_length=50)),
                ('app', models.CharField(default='app', max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=256)),
                ('streamkey', models.CharField(max_length=512)),
                ('protocol', models.CharField(choices=[('rtmp', 'RTMP')], default='rtmp', max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
